pipeline {
    agent any

    environment {
        POSTGRES_SECRET = credentials('jenkins-postgres-credentials')
    }

    stages {

        stage('Install dependencies') {
            steps {
                sh '''
                python3 -m venv venv
                . venv/bin/activate
                pip install --upgrade pip
                pip install -r "PyTest DQ Framework/requirements.txt"
                '''
            }
        }

        stage('Run PyTest') {
            steps {
                sh '''
                . venv/bin/activate

                pytest "PyTest DQ Framework/tests" -m parquet_data \
                    --db_host=postgres \
                    --db_port=5432 \
                    --db_name=mydatabase \
                    --db_user="$POSTGRES_SECRET_USR" \
                    --db_password="$POSTGRES_SECRET_PSW" \
                    --html="PyTest DQ Framework/html_report/index.html" \
                    --self-contained-html
                '''
            }
        }

        stage('Archive Test Report') {
            steps {
                archiveArtifacts artifacts: 'PyTest DQ Framework/html_report/**', allowEmptyArchive: true

                publishHTML(target: [
                    allowMissing: false,
                    keepAll: true,
                    reportDir: 'PyTest DQ Framework/html_report',
                    reportFiles: 'index.html',
                    reportName: 'HTML Data Quality Report'
                ])
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished. Cleaning workspace...'
        }
    }
}