pipeline {
    agent any
    stages {
        stage('Update Packages') {
            steps {
                script {
                    sh 'apt-get update'
                    sh 'apt-get install -y libpq-dev'
                }
            }
        }

        stage('Install Python') {
            steps {
                sh 'apt-get install -y python3 python3-pip python3-venv'
            }
        }

        stage('Clone Repository') {
            steps {
                script {
                    git branch: 'main', url: 'https://github.com/AnSpring/dqe-automation'
                }
            }
        }

        stage('Install Dependencies') {
            steps {
                script {
                    sh '''
                        python3 -m venv venv
                        . venv/bin/activate
                        pip install -r data_dev/requirements.txt
                    '''
                }
            }
        }

        stage('Run main') {
            steps {
                script {
                    sh '''
                        . venv/bin/activate
                        export PYTHONPATH=$WORKSPACE
                        python data_dev/main.py
                    '''
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline execution completed.'
        }

        success {
            echo 'Pipeline executed successfully!'

            archiveArtifacts artifacts: 'generated_report/report.html', fingerprint: true
        }

        failure {
            echo 'Pipeline failed. Please check the logs for details.'
        }
    }
}

